name:                hashpass
version:             0.1.0.0
github:              "SongWithoutWords/hashpass"
license:             BSD3
author:              "Ian McCall"
maintainer:          "ianmccall93@gmail.com"
copyright:           "Ian McCall"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SongWithoutWords/hashpass#readme>

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- bytestring-conversion
- containers
- cryptonite
- directory
- integer-logarithms
- memory
- optparse-applicative

library:
  source-dirs: src

executables:
  hashpass:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashpass

tests:
  hashpass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashpass
